version: "3"
services:
  database:
    image: mysql:8.0.27
    container_name: mysql_container
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "testdb"

  redis:
    image: redis
    container_name: redis_container
    ports:
      - "6379:6379"
